# O rolling update ter um controle mais fino para diminuir o risco de indisponibilidade da aplicacao. 
# Ele vai atualizando os poucos confome os parametros abaixo:
# maxSurge 1 -> pode ter ate 1 pod a mais do que eu pedi no arquivo - max 11 pods
# maxUnavailable 2 -> vai atualizar de 2 em 2
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: nginx-deployment
  name: nginx-deployment
spec:
  replicas: 10
  selector:
    matchLabels:
      app: nginx-deployment
  strategy: 
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 10%
      maxUnavailable: 25%
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nginx-deployment
    spec:
      containers:
      - image: nginx:1.16.0
        name: nginx
        resources: {}
status: {}
