apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ng-deploy
  name: ng-deploy  
spec:
  replicas: 3
  selector:
    matchLabels: 
      app: ng-deploy
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 2
  template:
    metadata:
      labels:
        app: ng-deploy
    spec:
      containers:
      - image: nginx:1.16.0
        name: nginx
        resources:
          limits:
            cpu: 0.7
            memory: 128Mi
          requests:
            cpu: 0.4
            memory: 64Mi
        
    
      
