apiVersion: v1
kind: Pod
metadata:
  labels:
    run: giropops
  name: giropops
spec:
  containers:
  - image: ubuntu
    name: ubuntu
    volumeMounts:
    - mountPath: /bodegami
      name: bodegami-dir    
    args:
    - sleep
    - "1800"
    resources:
      limits:
        cpu: "1"
        memory: "128Mi"
      requests:
        cpu: "0.5"
        memory: "64Mi"
  - image: nginx
    name: nginx
    volumeMounts:
    - mountPath: /bodegami
      name: bodegami-dir    
    resources:
      limits:
        cpu: "1"
        memory: "128Mi"
      requests:
        cpu: "0.5"
        memory: "64Mi"        
  dnsPolicy: ClusterFirst
  restartPolicy: Always
  volumes:
  - name: bodegami-dir
    emptyDir:
      sizeLimit: 256Mi